import Head from 'next/head'
import Hero from '../components/Banner'
import Slider from '../components/Slider'
import { SliderImages } from '../components/SliderData'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Best  Photo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero title={'The Best Photo'} info={'You can take any image from gallery'}/>
      <Slider SliderData={SliderImages}/>
    </div>
  )
}
