
import Head from 'next/head'
import Hero from '../components/Banner'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Best  Photo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero title={'The Best Photo'} info={'You can take any image from gallery'}/>
    </div>
  )
}
